"""Central error code constants."""

UNKNOWN_ERROR = "UNKNOWN_ERROR"
VALIDATION_FAILED = "VALIDATION_FAILED"
VERIFY_FAILED = "VERIFY_FAILED"
USER_CONFIRMATION_REQUIRED = "USER_CONFIRMATION_REQUIRED"

MCP_TOOL_MISSING = "MCP_TOOL_MISSING"
MCP_SERVER_UNAVAILABLE = "MCP_SERVER_UNAVAILABLE"
MCP_TOOL_FAILED = "MCP_TOOL_FAILED"

ACAD_COM_UNAVAILABLE = "ACAD_COM_UNAVAILABLE"
ACAD_COM_DEPENDENCY_MISSING = "ACAD_COM_DEPENDENCY_MISSING"
ACAD_DOC_UNAVAILABLE = "ACAD_DOC_UNAVAILABLE"
ACAD_COMMAND_TIMEOUT = "ACAD_COMMAND_TIMEOUT"
ACAD_RPC_FAILED = "ACAD_RPC_FAILED"

LISP_VALIDATE_FAILED = "LISP_VALIDATE_FAILED"
LISP_LOAD_FAILED = "LISP_LOAD_FAILED"
LISP_RUNTIME_FAILED = "LISP_RUNTIME_FAILED"
LISP_INTERACTIVE_FORBIDDEN = "LISP_INTERACTIVE_FORBIDDEN"

ACCORE_NOT_FOUND = "ACCORE_NOT_FOUND"
ACCORE_NONZERO_EXIT = "ACCORE_NONZERO_EXIT"
ACCORE_TIMEOUT = "ACCORE_TIMEOUT"
ACCORE_UNSUPPORTED_SCRIPT = "ACCORE_UNSUPPORTED_SCRIPT"
ACCORE_CONFIG_LOCKED = "ACCORE_CONFIG_LOCKED"

DWG_LOCKED = "DWG_LOCKED"
FILE_NOT_FOUND = "FILE_NOT_FOUND"
BACKUP_FAILED = "BACKUP_FAILED"
ROLLBACK_FAILED = "ROLLBACK_FAILED"
